### ISSUE TITLE
postgres fails to start on Viya 3.5

### ISSUE THREAD

**Issue by benformosa** [sassoftware/viya-ark#34]
I was unable to start a Viya 3.5 deployment using `playbooks/viya-mmsu/viya-services-start.yml`.

The deployment consists of :
* 2 stateful servers
* 2 microservices servers
* 1 spre server
* 2 CAS masters
* 20 CAS workers

I raised a track with SAS support, who indicated that another client, who had also recently upgraded from Viya 3.4, had the same issue.

Here's the error I encountered:

```
TASK [SAS Infrastructure Data Server - postgres] *****
fatal: [stateful0]: FAILED! => {
	"changed": true,
	"msg": "non-zero return code",
	"rc": 1,
	"stderr": "Shared connection to stateful0.example.com closed.\r\n",
	"stderr_lines": [
		"Shared connection to stateful0.example.com closed."
	],
	"stdout": ...
	"stdout_lines": [
		"CurrentLogFile=/opt/sas/viya/config/var/log/sasdatasvrc/postgres/pgpool0/startall_20191220_093825_293.log",
		"To see the progress, do: tail -f <log-file>",
		"ERROR: f_operate_node_request: Expired waiting for pgpool0 to be completed. Wait time: 120 seconds. The consul-template-operation-node service may be down.",
		"ERROR: f_operate_node_request: Failed PoolNode:All:Start for postgres",
		"ERROR: f_start_cluster: failed 'f_operate_node_request PoolNode:All:Start'. rC=1",
		"ERROR: main: failed 'f_start_cluster'. rC=1"
	]
}

```

**Comment by benformosa** [comment]
I was able to get the services started by using the `site.yml` playbook which is part of the Viya install/upgrade package.

The SAS support track numbers are 7612972300, 7612969144.

**Comment by erharb** [comment]
The [viya-services-start.yml](https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-mmsu/viya-services-start.yml) playbook does start consul first before going on to postgres, we can review the log from 7612969144 to try to put together what happened (StartAllServices.txt.sanitized).

**Comment by cuddlehub** [comment]
Can you send us the viya-services-vars.yml file in viya-mmsu? Thanks.

**Comment by sukcbb** [comment]
@erharb and @cuddlehub. I have just sent you though internal email. Thanks.

**Comment by cuddlehub** [comment]
Can you resend? or post the information for svs_label in the file? Thanks.

**Comment by erharb** [comment]
@sukcbb  can you post a cleaned version of the files here on this issue in github, maybe email is blocking the attachments?

**Comment by benformosa** [comment]
Hi @erharb, here's those details from my environment:

## Inventory
```yaml
AdminServices: micro0, micro1
CASServices: micro0, micro1
CognitiveComputingServices: micro0, micro1
CommandLine: micro0, micro1, prog, stateful0, stateful1, cascontroller0, cascontroller1, casworker0, casworker1, casworker2, casworker3, casworker4, casworker5, casworker6, casworker7, casworker8, casworker9, casworker10, casworker11, casworker12, casworker13, casworker14, casworker15, casworker16, casworker17, casworker18, casworker19
ComputeServer: prog
ComputeServices: prog
CoreServices: micro0, micro1
DataServices: micro0, micro1
GraphBuilderServices: micro0, micro1
HomeServices: micro0, micro1
Operations: prog
ReportServices: micro0, micro1
ReportViewerServices: micro0, micro1
StudioViya: prog
ThemeServices: micro0, micro1
configuratn: stateful0, stateful1
consul: stateful0
httpproxy: micro0, micro1, prog, stateful0, stateful1
pgpoolc: stateful0
programming: prog
rabbitmq: stateful0, stateful1
sas_casserver_primary: cascontroller0
sas_casserver_secondary: cascontroller1
sas_casserver_worker: casworker0, casworker1, casworker2, casworker3, casworker4, casworker5, casworker6, casworker7, casworker8, casworker9, casworker10, casworker11, casworker12, casworker13, casworker14, casworker15, casworker16, casworker17, casworker18, casworker19
sasdatasvrc: stateful0, stateful1
```

##  viya-services-vars.yml
```yaml
####################################################################
#### viya-services-vars.yml                                     ####
####################################################################
#### Author: SAS Institute Inc.                                 ####
####################################################################
---
svs_label: 3.5.20191028
#########################################
# Variables used in playbooks
#########################################
svas_retry_count: 3
svas_delay_timer: 2                   #seconds
enable_stray_cleanup: false           #stray processes cleanup
stray_process_count: 30               #0: list all
log_diskspace_minimum: 2097152000     #2GB
url_link: https                       #default https
```
