### ISSUE TITLE
Pre-upgrade: postgresql case sensitive hostname comparison

### ISSUE THREAD

**Issue by Carus11** [sassoftware/viya-ark#40]
In the pre upgrade playbook file:
https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-upgrade/pre_upgrade/verify-postgres-server.yml

line 201, 209:
```
        - name: Compare the secondary node_type between the PostgreSQL check output and vars.yml
          assert:
            that: ansible_fqdn in obtain_postgres_secondary_hostname.stdout
[....]
    - name: Compare the host names from the PostgreSQL check with the host names in the inventory file
      assert:
        that: ansible_fqdn in obtain_postgres_hostname.stdout
```
The assert will fail if the case does not match. 
I am wondering if this is a valid requirement as domain names are supposed to be case insensitive?
